# The main config file for your Jekyll template

# Site settings
title: Rishi Raj - Software Developer, Google Summer of Code Intern, Open Source Enthusiast               # used for the html title of every page
desc: >
  Hello, there! I am Rishi Raj. Software Developer, Open Source Enthusiast who has experience
  in ReactJS, AngularJS, Javascript and Laravel.



url: http://rishiraj.co      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: rishiraj824@gmail.com
author: Rishi Raj
twitter_username: rishiraj824
github_username: rishiraj824
github_source: rishiraj824.github.io

# Put your ga tracking code below
google_analytics: 'UA-30210543-1'

# Pagination settings
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
    enabled: true
    per_page: 15                          # number of posts to show per page
    permalink: '/articles/page/:num/'
    sort_field: 'date'
    sort_reverse: true


comments: true
# Discus Short Name
disqus:
  shortname: rishiraj-co
# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
    desc: Open Source Dev, Resources and Learnings
  - title: Projects
    url: /projects/
    desc: Lists all the projects done by me
  - title: Work
    url: /work/
    desc: Professional Dev
    desc: About me
  - title: Resume
    url: /assets/Resume.pdf

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-seo-tag
  - jekyll-paginate-v2

