# The main config file for your Jekyll template

# Site settings
title: Rishi Raj               # used for the html title of every page
desc: >
  Hello, there! I am Rishi Raj. I'm a Web Developer who has experience
  in ReactJS, AngularJS, Javascript, Laravel and Wordpress.



url: http://rishiraj.co      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: rishiraj824@gmail.com
author: Rishi Raj
twitter_username: rishirajloyola
github_username: rishiraj824
github_source: rishiraj824.github.io

# Put your ga tracking code below
google_analytics: 'UA-30210543-1'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Articles
    url: /articles/
    desc: What I'd like to share with you
  - title: Projects
    url: /projects/
    desc: What I love to spend time on
  - title: Work
    url: /work/
    desc: My Clients and Startups I Work For
  - title: About
    url: /about/
    desc: Know me a little

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

